//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class Lifestyle
    {
        public Lifestyle()
        {
            this.SpecialDiet = new HashSet<SpecialDiet>();
        }
    
        public int Id { get; set; }
        public string SmokeState { get; set; }
        public string SmokeStartAge { get; set; }
        public string SmokeQuitYear { get; set; }
        public string SmokeYear { get; set; }
        public string CigarettesPerDay { get; set; }
        public string DrinkState { get; set; }
        public string DrinkStartAge { get; set; }
        public string DrinkYear { get; set; }
        public string DrinkQuitYear { get; set; }
        public string DrinkPerDay { get; set; }
        public string DrinkCategory { get; set; }
        public string TeaPerDay { get; set; }
        public string CoffePerDay { get; set; }
        public string ExercisePerWeek { get; set; }
        public string ExerciseTime { get; set; }
        public string ExerciseDescription { get; set; }
        public string WeightChange { get; set; }
        public string WeightChangeNote { get; set; }
    
        public virtual ICollection<SpecialDiet> SpecialDiet { get; set; }
        public virtual PatBasicInfor PatBasicInfor { get; set; }
    }
    
}
