//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class ProphylaxisDrug
    {
        public int ID { get; set; }
        public string DrugName { get; set; }
        public int VisitRecordId { get; set; }
        public string PatBasicInforId { get; set; }
    
        public virtual PatBasicInfor PatBasicInfor { get; set; }
    }
    
}
